Repository cnosdb/cnosdb-isipho, pull requests merged in 2022-07, with the labels that each got.

#37 refactor : refactor kvcore read
  tskv/src/kvcore.rs
  tskv/src/memcache.rs
  tskv/src/tseries_family.rs
  tskv/src/tsm/reader.rs
Labels: enhancement, kv store

#42 refactor : fix most of clippy
  tskv/benches/kvcore_bench.rs
  tskv/src/forward_index/forward_index.rs
  tskv/src/kv_option.rs
  tskv/src/kvcore.rs
  tskv/src/lru_cache.rs
  tskv/src/memcache.rs
  tskv/src/record_file/errors.rs
  tskv/src/record_file/file.rs
  tskv/src/record_file/reader.rs
  tskv/src/record_file/writer.rs
  tskv/src/schema.rs
  tskv/src/summary.rs
  tskv/src/tsm/block.rs
  tskv/src/tsm/reader.rs
  tskv/src/tsm/writer.rs
  tskv/src/version_set.rs
  tskv/src/wal.rs
Labels: refactor

#59 #58 Update new roadmap
  README.md
Labels: documentation

#65 fix : change MAX_MEMCACHE_SIZE and MAX_IMMEMCACHE_NUM
  tskv/src/kv_option.rs
Labels: bug

#75 feat(delete) #51 : add delete interface for ts_family
  tskv/src/kvcore.rs
  tskv/src/memcache.rs
  tskv/src/tseries_family.rs
Labels: enhancement, feature, kv store

#79 feat(tsfamily) #70 : support add and del tsfamily and recover from su…
  config/config.toml
  config/src/lib.rs
  query/src/context.rs
  query/src/db.rs
  tskv/src/compaction/flush.rs
  tskv/src/context.rs
  tskv/src/kvcore.rs
  tskv/src/summary.rs
  tskv/src/tseries_family.rs
  tskv/src/version_set.rs
Labels: feature, kv store
